Repository entando-k8s/entando-k8s-service, pull requests merged in 2021-11, with the labels that each got.

#29 ENG-2802 undeploy of an EntandoDeBundle
  pom.xml
  src/main/java/org/entando/kubernetes/controller/EntandoDeBundleController.java
  src/main/java/org/entando/kubernetes/exception/BadRequestExceptionFactory.java
  src/main/java/org/entando/kubernetes/service/EntandoDeBundleService.java
  src/main/resources/application-dev.properties
  src/test/java/org/entando/kubernetes/controller/EntandoDeBundleControllerTest.java
  src/test/java/org/entando/kubernetes/service/EntandoDeBundleServiceTest.java
Labels: size/L

#30 ENG-2959 moving lib versions to parent
  .snyk
  pom.xml
Labels: size/M

#31 ENG-2962 Updating parent version
  pom.xml
Labels: size/XS, approved
